### ISSUE TITLE
Building psautohintexe with meson --backend=xcode fails

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/psautohint#82]
I tried Xcode and the command line. The same problem.

**Comment by khaledhosny** [comment]
You need to generate `version.h` by running `setup.py`, the simplest seems to be `python setup.py build_clib`.

**Comment by anthrotype** [comment]
try running python setup.py egg_info before building psautohintexe.
The version.h file is autogenerated by setuptools_scm from the git tags.

**Comment by schriftgestalt** [comment]
But it would make it easier for others to dip their toes into the code.

**Comment by khaledhosny** [comment]
meson build from #94 supports generating XCode project files, but I haven’t tried that.

**Comment by miguelsousa** [comment]
@schriftgestalt what if you submitted a PR? _That_ would be helpful

**Comment by anthrotype** [comment]
You should now be able to build the standalone autohintexe and the libpsautohint shared library using the meson build tool (see Readme).

Additionally, we now build a copy of the executable in the psautohint python package, so you could also grab it from there.

**Comment by anthrotype** [comment]
forgot to mention, of course meson can produce an Xcode project as well as ninja or other makefiles. Please refer to the meson docs

**Comment by anthrotype** [comment]
ehm.. actually it doesn't work, even with the latest meson from github master:

```
$ meson --backend=xcode _build libpsautohint
The Meson build system
Version: 0.48.0.dev1
Source dir: /Users/cosimolupo/Documents/Github/psautohint/libpsautohint
Build dir: /Users/cosimolupo/Documents/Github/psautohint/_build
Build type: native build
Traceback (most recent call last):
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/mesonmain.py", line 356, in run
    app.generate()
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/mesonmain.py", line 117, in generate
    self._generate(env)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/mesonmain.py", line 134, in _generate
    intr = interpreter.Interpreter(b)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreter.py", line 1914, in __init__
    self.parse_project()
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreterbase.py", line 365, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreterbase.py", line 705, in function_call
    return func(node, posargs, kwargs)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreterbase.py", line 133, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreter.py", line 2496, in func_project
    self.set_backend()
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/interpreter.py", line 2457, in set_backend
    self.backend = xcodebackend.XCodeBackend(self.build)
  File "/Users/cosimolupo/Documents/Github/meson/mesonbuild/backend/xcodebackend.py", line 27, in __init__
    self.project_uid = self.environment.coredata.guid.replace('-', '')[:24]
AttributeError: 'CoreData' object has no attribute 'guid'
```

not sure what's going on.
Maybe related
https://github.com/mesonbuild/meson/issues/337
https://github.com/mesonbuild/meson/pull/416

**Comment by khaledhosny** [comment]
Looks like the XCode generator is not well maintained, bug might have been introduced with commit https://github.com/mesonbuild/meson/commit/c6e03b953530e111c99b25b01bcd59d176703dd6. This line in `backend/xcodebackend.py`:
```
self.project_uid = self.environment.coredata.guid.replace('-', '')[:24]
```
should probably be:
```
self.project_uid = self.environment.coredata.lang_guids['default'].replace('-', '')[:24]
```

**Comment by anthrotype** [comment]
after applying that patch now I get this other error:

```
$ meson --backend=xcode _build libpsautohint/
The Meson build system
Version: 0.48.0.dev1
Source dir: /home/clupo/Github/psautohint/libpsautohint
Build dir: /home/clupo/Github/psautohint/_build
Build type: native build
Project name: psautohint
Project version: 1.7.0
Native C compiler: cc (gcc 7.3.0 "cc (Debian 7.3.0-5) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found git repository at /home/clupo/Github/psautohint
Library m found: YES
Build targets in project: 3
Traceback (most recent call last):
  File "/home/clupo/Github/meson/mesonbuild/mesonmain.py", line 356, in run
    app.generate()
  File "/home/clupo/Github/meson/mesonbuild/mesonmain.py", line 117, in generate
    self._generate(env)
  File "/home/clupo/Github/meson/mesonbuild/mesonmain.py", line 166, in _generate
    intr.backend.generate(intr)
  File "/home/clupo/Github/meson/mesonbuild/backend/xcodebackend.py", line 71, in generate
    self.generate_filemap()
  File "/home/clupo/Github/meson/mesonbuild/backend/xcodebackend.py", line 118, in generate_filemap
    for o in t.objects:
AttributeError: 'CustomTarget' object has no attribute 'objects'
```

Perhaps with hindsight cmake would have been a better choice, but we can't change 3 build systems in a week.

**Comment by anthrotype** [comment]
btw, looks like the offending line is exactly the one that calls `vcs_tag` to generate version.h. If I remove that, then (with your patch above), I can generate an xcodeproject file.

**Comment by anthrotype** [comment]
shall I submit that patch upstream or you'do it?

**Comment by khaledhosny** [comment]
I updated the README to drop any mention of Meson. People who want to use it can always use the Ninja backend, or nag upstream to support other backends. I can’t test on macOS right now, so please report/send patches upstream if you feel so.

**Comment by anthrotype** [comment]
sounds good to me

**Comment by schriftgestalt** [comment]
I didn't mean to trigger such a long discussion. And the existing Xcode project file is fine, so no need to generate one. I was just asking if (and how) to potentially add the script to it. But its fine now.

**Comment by khaledhosny** [comment]
Closing now.

**Comment by schriftgestalt** [comment]
I’m updating the Xcode project file and need some help. What (git) command would give me the version number that will be written to version.h by setup.py (currently: `1.9.2b3.dev6+g47944ed.d20190422`)?
When I run `git describe`, I get `v1.9.2b2-6-g47944ed`
